### PR TITLE
 make deleteType async friendly -sort of-

### PR DESCRIPTION
**Pull request by JoeZ99**

### CODE REVIEW

**Comment by JoeZ99** [comment]
@carlosescri 
I don't know if this is enough. Guess it's a "bare minimum" , but maybe when trying to index during a delete type operation, would be better to return some message instead of throwing an `IndexingInProgress` ...

I don't know, please check the new doc:
https://github.com/doofinder/php-doofinder/tree/async_delete_type

**Comment by carlosescri** [comment]
@JoeZ99, Magently implemented this for requests limits (I've sent you this from Slack but you didn't notice):

https://github.com/magently/doofinder-magento2/commit/46985ef09861076f27ecadda4aab847f10992c59#diff-dafb45c6676be8384257091b7701eb47

This makes a call until success or until it fails 3 times, waiting always 1 second. We could use something like that but incrementing sleeping time like Celery does when there's no connection to the queue.

**Comment by carlosescri** [comment]
Your code looks OK for me but throttling inside the library would be a great addition. This way the user doesn't have to deal with exceptions about commands that must wait until there's no other option. But probably that's a different issue.

**Comment by JoeZ99** [comment]
Ok , I guess we could add the feature of auto-adjusting response with throttle inside the library, but that's another issue.

But in the throttling case, you know if you wait a second you're almost certain the request will be accepted, son three trials with one second sleep each is certainly a safe bet.

In this case, though we don't know how long will it be, I would add some kind of "timeout" parameter somewhere that would mean how long to wait if there's some locking. If that parameter is not set, then the exception is raised. If it's set, then the index attempt is retried until that timeout expires.

It could be a constructor argument for the client object or it could or a positional argument in the `add_item`, `delete_item`, `update_items` , `delete_items` methods.


What do you think??

**Comment by carlosescri** [comment]
I think it's better to pass the argument to the client constructor.

**Comment by carlosescri** [comment]
For blocking ops...

Timeout is used when you don't get a response from a resource but, if you ask, we are returning a response saying the resource is busy working in the index. I think retrying is better in this case and we can raise an exception after a limit of retries that may be configurable to avoid _infinite retries_.

```
# PSEUDOCODE
$client->deleteDatatype('product'); // don't wait
$client->updateItem('product', ...); // immediately raises an exception
```

```
# PSEUDOCODE
$client->deleteDatatype('product', true); // wait, if op is not finished in max retries, raises an exception
$client->updateItem('product', ...); // no exception is raised
```

In the first case you have more control but you have to control everything yourself. In the other case you can rely on the client and control only one exception when there's no other option because the operation took too much time.

Finally think about how we are going to implement this:

- Ask Doofinder each second: too much requests for something async, it's better to be patience so we can space calls increasing wait time.
- Wait N seconds (timeout) and ask: Why blocking a script a fixed amount of time if it may be faster than expected?

Just thinking...

**Comment by carlosescri** [comment]
Regarding the PR:

- Is this tested somehow?
- If so, you can make the release :-)

**Comment by carlosescri** [comment]
And the remove references to versioning in the PHP code if we're not updating it when creating a new release 😉 .

**Comment by JoeZ99** [comment]
Don't understand your last remark.

**Comment by JoeZ99** [comment]
OK then.

   * `delete_datatype('product', true)`  keeps checking , maybe with one check every second (or every two seconds) until it certain time is passed. That's a sensitive default, but on the constructor we can alter that.

    * We need to implement an API call to check if there's an indexing lock on the search engine

**Comment by carlosescri** [comment]
We have this:

https://github.com/doofinder/php-doofinder/blob/60aa0600a8618e1c81c336c113eb3bbf210815f7/src/Search/Client.php#L40

And the latest version is: 

https://github.com/doofinder/php-doofinder/releases/tag/v5.5.1

**Pull request merged**
